name: Congruence
version: 1.2.4
date: 2022-04-27
description: |
    Congruence subgroups of SL(2,Integers)

authors:
    - name: Ann Dooms
      url: http://homepages.vub.ac.be/~andooms
    - name: Eric Jespers
      url: http://homepages.vub.ac.be/~efjesper
    - name: Olexandr Konovalov
      url: https://alex-konovalov.github.io/
    - name: Helena Verrill
      url: http://www.math.lsu.edu/~verrill

maintainers:
    - name: Ann Dooms
      url: http://homepages.vub.ac.be/~andooms
    - name: Olexandr Konovalov
      url: https://alex-konovalov.github.io/
    - name: Helena Verrill
      url: http://www.math.lsu.edu/~verrill

GAP: ">=4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/congruence
readme: README.md
packageinfo: https://gap-packages.github.io/congruence/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/congruence/releases/download/v1.2.4/congruence-1.2.4.tar.gz

abstract: |
    The <span class="pkgname">Congruence </span> package provides functions to construct several types of canonical congruence subgroups in SL_2(Z), and also intersections of a finite number of such subgroups. Furthermore, it implements the algorithm for generating Farey symbols for congruence subgroups and using them to produce a system of independent generators for these subgroups

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
